# Generated by Django 5.0.14 on 2025-07-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("club", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voter_name", models.CharField(blank=True, max_length=100)),
                ("voter_country", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "player_1st",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_votes",
                        to="ballon_dor.player",
                    ),
                ),
                (
                    "player_2nd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_votes",
                        to="ballon_dor.player",
                    ),
                ),
                (
                    "player_3rd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_votes",
                        to="ballon_dor.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BallonDorResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("club_at_award", models.CharField(blank=True, max_length=100)),
                ("nationality_at_award", models.CharField(blank=True, max_length=100)),
                ("points", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ballon_dor.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "player"), ("year", "rank")},
            },
        ),
    ]
