# Generated by Django 5.2.4 on 2025-07-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ballondorresult",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="player",
            name="club",
        ),
        migrations.AddField(
            model_name="candidate",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ballon_dor.club",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(blank=True, upload_to="players/"),
        ),
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, upload_to="clubs/"),
        ),
        migrations.AddField(
            model_name="nationalteam",
            name="flag",
            field=models.ImageField(blank=True, upload_to="flags/"),
        ),
        migrations.AddField(
            model_name="player",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="players/"),
        ),
        migrations.AlterField(
            model_name="ballondorresult",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="ballondorresult",
            constraint=models.UniqueConstraint(
                fields=("year", "rank"), name="unique_rank_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="ballondorresult",
            constraint=models.UniqueConstraint(
                fields=("year", "player"), name="unique_player_per_year"
            ),
        ),
    ]
