# Generated by Django 5.2.4 on 2025-07-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0002_alter_ballondorresult_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, upload_to="logos/"),
        ),
    ]
