# Generated by Django 5.0.14 on 2025-07-04 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0002_candidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NationalTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="vote",
            name="year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="ballondorresult",
            name="club_at_award",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ballon_dor.club"
            ),
        ),
        migrations.AlterField(
            model_name="ballondorresult",
            name="nationality_at_award",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ballon_dor.nationalteam",
            ),
        ),
    ]
