# Generated by Django 5.0.14 on 2025-07-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0003_club_nationalteam_vote_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ballondorresult",
            unique_together={("year", "rank", "player")},
        ),
    ]
