# Generated by Django 5.2.4 on 2025-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0003_alter_club_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vote",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
