# Generated by Django 5.2.4 on 2025-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0004_vote_email_vote_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="token",
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
