# Generated by Django 5.0.14 on 2025-07-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0004_alter_ballondorresult_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ballondorresult",
            unique_together={("year", "player"), ("year", "rank")},
        ),
    ]
