# Generated by Django 5.2.4 on 2025-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0005_alter_ballondorresult_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballondorresult",
            name="rank",
            field=models.CharField(
                choices=[("1", "First"), ("2", "Second"), ("3", "Third")],
                default="",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
