# Generated by Django 5.0.14 on 2025-07-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0005_alter_ballondorresult_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballondorresult",
            name="rank",
            field=models.CharField(
                choices=[("1", "First"), ("2", "Second"), ("3", "Third")],
                default="",
                max_length=2,
            ),
        ),
    ]
