# Generated by Django 5.2.4 on 2025-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0005_vote_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voter_country",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
