# Generated by Django 5.0.14 on 2025-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0006_alter_ballondorresult_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballondorresult",
            name="rank",
            field=models.IntegerField(),
        ),
    ]
