# Generated by Django 5.2.4 on 2025-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0006_alter_vote_voter_country"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("year", "email"), name="unique_email_per_year"
            ),
        ),
    ]
