# Generated by Django 5.2.4 on 2025-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0009_add_essential_candidate_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="stats",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(blank=True, upload_to="candidate/"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="trophies_won",
            field=models.TextField(
                blank=True,
                help_text="Major trophies won this season (e.g., Champions League, Premier League)",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="why_contender",
            field=models.TextField(
                blank=True,
                help_text="Brief explanation of why they deserve the Ballon d'Or",
            ),
        ),
    ]
