# Generated by Django 5.2.4 on 2025-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ballon_dor",
            "0010_remove_candidate_achievements_remove_candidate_stats_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(blank=True, max_length=500, upload_to="candidate/"),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, max_length=500, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="nationalteam",
            name="flag",
            field=models.ImageField(blank=True, max_length=500, upload_to="flags/"),
        ),
        migrations.AlterField(
            model_name="player",
            name="profile_pic",
            field=models.ImageField(blank=True, max_length=500, upload_to="players/"),
        ),
    ]
