# Generated by Django 5.2.4 on 2025-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0011_alter_candidate_image_alter_club_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="ballondor_2025/"
            ),
        ),
    ]
