# Generated by Django 5.2.4 on 2025-08-05 14:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0012_alter_candidate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="nationalteam",
            name="flag",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
