# Generated by Django 5.2.4 on 2026-10-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0014_candidate_position_and_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="awards",
            field=models.TextField(
                blank=True,
                help_text="Individual awards, ONE PER LINE (e.g. World Cup Golden Ball, Premier League Player of the Season)",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="expected_goals",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Attackers/attacking mids: expected goals (xG) this season",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.CharField(
                choices=[
                    ("FWD", "Forward"),
                    ("CAM", "Attacking Midfielder"),
                    ("MID", "Midfielder"),
                    ("DEF", "Defender"),
                ],
                default="FWD",
                help_text="Controls which stats show on the profile page",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="trophies_won",
            field=models.TextField(
                blank=True,
                help_text="Trophies won, ONE PER LINE (e.g. Champions League, Premier League)",
            ),
        ),
    ]
