# Generated by Django 5.2.4 on 2026-10-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ballon_dor", "0015_candidate_cam_xg_awards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="voter_name",
        ),
    ]
